spring.application.name=odm



server.port=8081
odm.base-url=http://localhost:9060/DecisionService/rest/v1
odm.username=odmAdmin
odm.password=odmAdmin
odm.credit-immobilier-path=/deploiement_requests/1.0/evaluerCreditImmobilier
odm.credit-consommation-path= /deploiement_requests/1.0/evaluerCreditConsommation
odm.virement-path= /deploiement_requests/1.0/evaluerVirement
odm.assurance-path= /deploiement_requests/1.0/evaluerAssurance
odm.carte-path= /deploiement_requests/1.0/evaluerCarte